### ISSUE TITLE
Original source now GitHub

### ISSUE THREAD

**Issue by MichaelKetting** [onekosha/LicenseHeaderManager#1]
Hi Sandy! 

Noticed your copy/fork of LicenseHeaderManager and wanted to let you know we've just moved the Mercurial sources over to GitHub at https://github.com/rubicon-oss/LicenseHeaderManager . In case you'd like to do an official fork/pull-request :)

Best regards, Michael

**Comment by onekosha** [comment]
Hi Michael!

I will use an official code of project.

Thank you
